config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :pages do 
    member do 
      get :delete
    end
  end

  resources :accounts do
    member do
      get :delete
    end
  end


  resources :stocks do 
    member do 
      get :delete
    end
    collection { post :import }
    collection { get :bulk_upload }
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord

  has_many :stocks

  scope :sorted, lambda { order("stock.dividend_yield ASC") }


  def self.monthly_income
    @accounts = Account.all
    @stocks = Stock.all    
    @date = Date.today
    monthly_income = Hash.new 
    monthly_income = {:january_income => 0, :february_income => 0, :march_income => 0, :april_income => 0, :may_income => 0,
                :june_income => 0, :july_income => 0, :august_income => 0, :september_income => 0, :october_income => 0,
                :november_income => 0, :december_income => 0}
    count = 1

    unless Account.last.nil?
      until count > Account.last.id
        if Account.exists?(:id => count)
          account = @accounts.find(count)
          stock = @accounts.find(count).stocks
          stock.each do |s|
            monthly_income[:january_income]   += s.january_income
            monthly_income[:february_income]  += s.february_income
            monthly_income[:march_income]     += s.march_income
            monthly_income[:april_income]     += s.april_income
            monthly_income[:may_income]       += s.may_income
            monthly_income[:june_income]      += s.june_income
            monthly_income[:july_income]      += s.july_income
            monthly_income[:august_income]    += s.august_income
            monthly_income[:september_income] += s.septermber_income
            monthly_income[:october_income]   += s.october_income
            monthly_income[:november_income]  += s.novemeber_income
            monthly_income[:december_income]  += s.december_income
          end
          account.january_income = monthly_income[:january_income]
          account.february_income = monthly_income[:february_income]   
          account.march_income =  monthly_income[:march_income]     
          account.april_income =  monthly_income[:april_income]     
          account.may_income =  monthly_income[:may_income]       
          account.june_income =  monthly_income[:june_income]     
          account.july_income =  monthly_income[:july_income]      
          account.august_income =  monthly_income[:august_income]    
          account.septermber_income =  monthly_income[:september_income] 
          account.october_income =  monthly_income[:october_income]   
          account.novemeber_income =  monthly_income[:november_income]  
          account.december_income =  monthly_income[:december_income]  
          puts monthly_income.inspect 
          account.save
          monthly_income = {:january_income => 0, :february_income => 0, :march_income => 0, :april_income => 0, :may_income => 0,
                      :june_income => 0, :july_income => 0, :august_income => 0, :september_income => 0, :october_income => 0,
                      :november_income => 0, :december_income => 0}                  
          count += 1
        else
          count += 1
        end
      end
    end
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  attr_accessor :sum, :m

  # before_action :require_login
  before_action :set_month, :only => [:index, :show]
  before_action :set_date, :only => [:index, :show]  

  def index
    @accounts = Account.all
    @stocks = Stock.all
    @sum = 0
    Account.monthly_income
  end

  def show 
    @account = Account.find(params[:id]) 
    @stocks = Account.find(params[:id]).stocks
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      flash[:notice] = "Congratulations you have just added #{@account.account_name}."
      redirect_to(root_path)
    else
      render ('new')
    end
  end

  def edit
    @account = Account.find(params[:id])
  end

  def update
    @account = Account.find(params[:id])
    if @account.update_attributes(account_params)
      flash[:notice] = "Nicely done!"
      redirect_to(account_path)
    else
      render('edit')
    end
  end

  def delete
    @account = Account.find(params[:id])
  end

  def destroy
    @account = Account.find(params[:id])
    @account.stocks.destroy_all
    @account.destroy
    flash[:notice] = "You have successfully deleted #{@account.account_name}"
    redirect_to(root_path)
  end

  private

  def account_params
    params.require(:account).permit(:account_name, :account_value, :january_income, :february_income,
                                    :march_income, :april_income, :may_income, :june_income, :july_income,
                                    :august_income, :septermber_income, :october_income, :november_income,
                                    :december_income)
  end

  def set_month
    @stocks = Stock.all
    @accounts = Account.all
    @date = Date.today
    month = @date.strftime("%B").downcase


    @m = "#{month}_income"
  end

  def set_date
    @date = Date.today
    @date = @date.strftime("%B")
  end


end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<table>
  <tr>
    <th>Account Name:</th>
    <td><%= f.text_field(:account_name) %></td>
  </tr>
</table>

app/views/accounts/delete.html.erb
<%= form_for(@account, :method => 'delete') do |f| %>

  <p>Are you sure you want to delete this account?</p>

  <p>Account Name: <%= f.object.account_name %></p>

  <%= f.submit('Delete Account') %>

<% end %>

app/views/accounts/edit.html.erb
<div class="new_stock_header">
  <h2>Edit Account Form</h2>

  <%= form_for(@account) do |f| %>
  
    <%= render(:partial => 'form', :locals => {:f => f})  %>

  <div class="form-buttons" style="text-align: left !important;">
    <%= f.submit('New Account') %>
  </div>

  <% end %>
</div>

app/views/accounts/index.html.erb
<% case @date %>
    <% when 'January' %>
      <% @stocks.each do |stock| %>
        <% (@sum += stock.january_income) %>
      <% end %>
      <% when 'February' %>
      <% @stocks.each do |stock| %>
        <% @sum += stock.february_income %>
      <% end %>
      <% when 'March' %>
      <% @stocks.each do |stock| %>
        <% @sum += stock.march_income %>
      <% end %>
      <% when 'April' %>
      <% @stocks.each do |stock| %>
        <% @sum += stock.april_income %>
      <% end %>
      <% when 'May' %>
      <% @stocks.each do |stock| %>
        <% @sum += stock.may_income %>
      <% end %>
      <% when 'June' %>
      <% @stocks.each do |stock| %>
        <% @sum += stock.june_income %>
      <% end %>
      <% when 'July' %>
      <% @stocks.each do |stock| %>
        <% @sum += stock.july_income %>
      <% end %>
      <% when 'August' %>
      <% @stocks.each do |stock| %>
        <% @sum += stock.august_income %>
      <% end %>
      <% when 'September' %>
      <% @stocks.each do |stock| %>
        <% @sum += stock.septermber_income %>
      <% end %>
      <% when 'October' %>
      <% @stocks.each do |stock| %>
        <% @sum += stock.october_income %>
      <% end %>
      <% when 'November' %>
      <% @stocks.each do |stock| %>
        <% @sum += stock.november_income %>
      <% end %>
      <% when 'December' %>
      <% @stocks.each do |stock| %>
        <% @sum += stock.december_income %>
      <% end %>
    <% end %>

<div class="container">
  <div>
    <h3>Accounts</h3>
    <p class="account-text">Below lists all of your accounts, click on an account to view details on that account specifically. The section below this list will outline what your projected income is for that specific account. Also feel free to click on the account name and that is another way to determine what stocks are producing that income.</p>
  </div>
  <div>
    <table class="table table-striped table-bordered">
      <tr style="border: 1px solid black;">
        <th>Totals</th>
        <td><%= @date == 'January'   ? number_to_currency(@sum)  : link_to('Jan') %></td>
        <td><%= @date == 'February'  ? number_to_currency(@sum)  : link_to('Feb') %></td>
        <td><%= @date == 'March'     ? number_to_currency(@sum)  : link_to('Mar') %></td>
        <td><%= @date == 'April'     ? number_to_currency(@sum)  : link_to('Apr') %></td>
        <td><%= @date == 'May'       ? number_to_currency(@sum)  : link_to('May') %></td>
        <td><%= @date == 'June'      ? number_to_currency(@sum)  : link_to('Jun') %></td>
        <td><%= @date == 'July'      ? number_to_currency(@sum)  : link_to('Jul') %></td>
        <td><%= @date == 'August'    ? number_to_currency(@sum)  : link_to('Aug') %></td>
        <td><%= @date == 'September' ? number_to_currency(@sum)  : link_to('Sep') %></td>
        <td><%= @date == 'October'   ? number_to_currency(@sum)  : link_to('Oct') %></td>
        <td><%= @date == 'November'  ? number_to_currency(@sum)  : link_to('Nov') %></td>
        <td><%= @date == 'December'  ? number_to_currency(@sum)  : link_to('Dec') %></td>
      </tr>
    </table>
  </div>
</div>

<div class="container">
  <% @accounts.each do |account| %>
   <button class="btn-info" style="margin-bottom: 20px;padding: 5px;border-radius: 6px;">
      <%= link_to account.account_name, account_path(account), {:class => "account_links"} %>
    </button>
  <% end %>
</div>

<div class="container">
  <div class="month-section">
    <h3><%= @date %></h3>

    <p>Expected Income: <span style="color: green;"><%= number_to_currency(@sum, :precision => 2) %></span></p>
  </div>

  <% @accounts.each do |account| %>
    <button class="btn-info" style="margin-bottom: 20px;padding: 5px;border-radius: 6px;">
      <%= account.account_name %>: 
        <%= number_to_currency(account.send(@m)) %>
    </button>
  <% end %>

  <div>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Ticker</th>
      <th>Shares</th>
      <th>Account</th>
      <th>Ex-Date</th>
      <th>Pay Date</th>
      <th>Expected Income</th>
    </tr>
  </thead>
  <tbody>
    <% @stocks.each do |stock| %>
    <tr>
    <% case @date %>
    <% when 'January' %>
      <% if stock.january_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.january_income, :precision => 2) %></td>
      <% end %>
      <% when 'February' %>
      <% if stock.february_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.february_income, :precision => 2) %></td>
      <% end %>
      <% when 'March' %>
      <% if stock.march_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.march_income, :precision => 2) %></td>
      <% end %>
      <% when 'April' %>
      <% if stock.april_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.april_income, :precision => 2) %></td>
      <% end %>   
      <% when 'May' %>
      <% if stock.may_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.may_income, :precision => 2) %></td>
      <% end %>    
      <% when 'June' %>
      <% if stock.june_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.june_income, :precision => 2) %></td>
      <% end %>
      <% when 'July' %>
      <% if stock.july_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.july_income, :precision => 2) %></td>
      <% end %>
      <% when 'August' %>
      <% if stock.august_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.august_income, :precision => 2) %></td>
      <% end %>
      <% when 'September' %>
      <% if stock.septermber_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.septermber_income, :precision => 2) %></td>
      <% end %>
      <% when 'October' %>
      <% if stock.october_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.october_income, :precision => 2) %></td>
      <% end %>
      <% when 'November' %>
      <% if stock.novemeber_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.novemeber_income, :precision => 2) %></td>
      <% end %>
      <% when 'December' %>
      <% if stock.december_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.december_income, :precision => 2) %></td>
      <% end %>
    <% end %>
    </tr>
    <% end %>
  </tbody>
  </table>
    
  </div>
</div>

app/views/accounts/new.html.erb
<div class="new_stock_header">
  <h2>New Account Form</h2>

  <%= form_for(@account) do |f| %>
  
    <%= render(:partial => 'form', :locals => {:f => f})  %>

  <div class="form-buttons" style="text-align: left !important;">
    <%= f.submit('New Account') %>
  </div>

  <% end %>
</div>

app/views/accounts/show.html.erb
<div class="container">
  <h3>Portfolio: <span style="color: green;"><%= @account.account_name %></span></h3>
  <p>Account ID: <strong><%= @account.id %></strong></p>
  <p>Expected <%= @date %> Income: <span style="color: green;"><%= number_to_currency(@account.send(@m)) %></span></p>
  <button class="btn-success btn-sm">
    <%= link_to 'Edit', edit_account_path(@account), {:class => 'account_links'} %>
  </button>
  <button class="btn-success btn-sm" >
    <%= link_to 'Add Stock', new_stock_path, {:class => 'account_links'} %>
  </button>
    <button class="btn-danger btn-sm" style="margin-bottom: 20px;">
    <%= link_to 'Delete', delete_account_path(@account), {:class => 'account_links'} %>
  </button>
</div>

<div class="container">
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Ticker</th>
      <th>Shares</th>
      <th>Account</th>
      <th>Ex-Date</th>
      <th>Pay Date</th>
      <th>Expected Income</th>
    </tr>
  </thead>
  <tbody>
    <% @stocks.each do |stock| %>
    <tr>
    <% case @date %>
    <% when 'January' %>
      <% if stock.january_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.january_income, :precision => 2) %></td>
      <% end %>
      <% when 'February' %>
      <% if stock.february_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.february_income, :precision => 2) %></td>
      <% end %>
      <% when 'March' %>
      <% if stock.march_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.march_income, :precision => 2) %></td>
      <% end %>
      <% when 'April' %>
      <% if stock.april_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.april_income, :precision => 2) %></td>
      <% end %>   
      <% when 'May' %>
      <% if stock.may_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.may_income, :precision => 2) %></td>
      <% end %>    
      <% when 'June' %>
      <% if stock.june_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.june_income, :precision => 2) %></td>
      <% end %>
      <% when 'July' %>
      <% if stock.july_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.july_income, :precision => 2) %></td>
      <% end %>
      <% when 'August' %>
      <% if stock.august_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.august_income, :precision => 2) %></td>
      <% end %>
      <% when 'September' %>
      <% if stock.septermber_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.septermber_income, :precision => 2) %></td>
      <% end %>
      <% when 'October' %>
      <% if stock.october_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.october_income, :precision => 2) %></td>
      <% end %>
      <% when 'November' %>
      <% if stock.novemeber_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.novemeber_income, :precision => 2) %></td>
      <% end %>
      <% when 'December' %>
      <% if stock.december_income > 0 %>
        <td><%= stock.ticker %></td>
        <td><%= stock.shares %></td>
        <td><%= stock.account.account_name %></td>
        <td><%= stock.ex_date %></td>
        <td></td>
        <td><%= number_to_currency(stock.december_income, :precision => 2) %></td>
      <% end %>
    <% end %>
    </tr>
    <% end %>
  </tbody>
  </table>
    
  </div>